# docker volume create --name=mongodb_discrete_volume
# docker volume create --name=corilus_discrete_volume
# docker volume create --name=recommender_discrete_volume
version: '3.2'
services:
  bookrs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3990:3000'
    environment:
      ROOT_URL: http://picasso.experiments.cs.kuleuven.be:3990/
      MONGO_URL: mongodb+srv://admin:admin@cluster0.8qwmt.mongodb.net/goodread-books?retryWrites=true&w=majority
      PORT: 3000
